"""Remove landing_pad table

Revision ID: 55deb78c8204
Revises: 6682e53c5f8d
Create Date: 2023-04-26 21:34:48.696072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55deb78c8204'
down_revision = '6682e53c5f8d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('station', sa.Column('landing_pad', sa.Integer(), nullable=True))
    op.drop_constraint('station_landing_pad_id_fkey', 'station', type_='foreignkey')
    op.drop_column('station', 'landing_pad_id')
    op.drop_table('landing_pad')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('station', sa.Column('landing_pad_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('station_landing_pad_id_fkey', 'station', 'landing_pad', ['landing_pad_id'], ['id'])
    op.drop_column('station', 'landing_pad')
    op.create_table('landing_pad',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('size', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='landing_pad_pkey')
    )
    # ### end Alembic commands ###
