"""Add price to import/export commodities

Revision ID: 6682e53c5f8d
Revises: 4a83fffdeec0
Create Date: 2023-04-26 21:32:44.079537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6682e53c5f8d'
down_revision = '4a83fffdeec0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('station_export_commodities', sa.Column('price', sa.Integer(), nullable=True))
    op.add_column('station_export_commodities', sa.Column('stock', sa.Integer(), nullable=True))
    op.add_column('station_import_commodities', sa.Column('price', sa.Integer(), nullable=True))
    op.add_column('station_import_commodities', sa.Column('demand', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('station_import_commodities', 'demand')
    op.drop_column('station_import_commodities', 'price')
    op.drop_column('station_export_commodities', 'stock')
    op.drop_column('station_export_commodities', 'price')
    # ### end Alembic commands ###
