"""Add system_id to station table

Revision ID: 86b681ed8a27
Revises: 55deb78c8204
Create Date: 2023-04-26 21:41:05.426188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86b681ed8a27'
down_revision = '55deb78c8204'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('station', sa.Column('system_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'station', 'system', ['system_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'station', type_='foreignkey')
    op.drop_column('station', 'system_id')
    # ### end Alembic commands ###
