"""Remove security table

Revision ID: af98776b7ab1
Revises: 9a7d455aaae1
Create Date: 2023-04-27 02:42:34.562517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af98776b7ab1'
down_revision = '9a7d455aaae1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('security_system_map', sa.Column('security', sa.String(), nullable=True))
    op.drop_constraint('security_system_map_security_id_fkey', 'security_system_map', type_='foreignkey')
    op.drop_column('security_system_map', 'security_id')
    op.add_column('system', sa.Column('security', sa.String(), nullable=True))
    op.drop_constraint('system_security_id_fkey', 'system', type_='foreignkey')
    op.drop_column('system', 'security_id')
    op.drop_table('security')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system', sa.Column('security_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('system_security_id_fkey', 'system', 'security', ['security_id'], ['id'])
    op.drop_column('system', 'security')
    op.add_column('security_system_map', sa.Column('security_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('security_system_map_security_id_fkey', 'security_system_map', 'security', ['security_id'], ['id'])
    op.drop_column('security_system_map', 'security')
    op.create_table('security',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='security_pkey')
    )
    # ### end Alembic commands ###
